### ISSUE TITLE
Clicking the X on the window does not kill the emu

### ISSUE THREAD

**Issue by jkbenaim** [tj90241/cen64#24]
Clicking the X on the window does not make cen64 quit when using the multithreading branch.

**Comment by tj90241** [comment]
Just merged multithreading into master and angrylion-rdp, but issue is still present.

**Comment by mikeryan** [comment]
Using ```pthread_cancel``` instead of ```pthread_join``` makes the problem go away but might not be the correct solution.

**Comment by tj90241** [comment]
I've been avoid doing that because the would-be cancelled thread can be in the middle of a save operation or something. You need to cancel during a safepoint or something to avoid major WTFs down the road.

I guess what I'm saying is: I'd rather invest the time into fixing it "the right way", rather than doing some quick patchwork that will have to be fixed later anyways.
