### ISSUE TITLE
There are sometimes 4 controllers connected

### ISSUE THREAD

**Issue by jkbenaim** [tj90241/cen64#38]
![benzedrine](https://cloud.githubusercontent.com/assets/2214896/12898193/6fe587c6-ce79-11e5-90bd-04890aff86e3.png)

There seems to be 4 controllers connected by default. I'm not sure if this is intentional or not, but it should at least be configurable.

(The above screenshot is for showing that a controller is connected to each of the 4 ports. The text happens to indicate that an error has occurred, but that is the correct behavior.)

**Comment by vgturtle127** [comment]
@jkbenaim Why would having 4 controllers plugged in cause an error in the N64 game? That would seem silly to me. I mean, I don't think I have heard of any game that had an error message for when 4 controllers are connected. I wonder if this causes issues in other games?

What game is this, and do you know what the text says?

**Comment by Fendoroid** [comment]
I don't own the game, but the message says no useful information. It says:
"Due to uncorrect report, you can't continue to play. Please reset."

**Comment by mikeryan** [comment]
This behavior is erroneous because the system should not report controllers as plugged in if they are not present. Without specifying -controller num=2 (through 4) on the command line, the system and Pokemon Stadium 2 should report them as unplugged.

The Japanese error message is unrelated to the controller plugin issue.

**Comment by jkbenaim** [comment]
While attempting to take a more appropriate screenshot for this issue, I discovered something interesting! Pokemon Stadium 2 (USA) only sees 1 controller, while the Japanese version of the same game sees 4 controllers.

Pokemon Stadium 2 (USA):
![usa](https://cloud.githubusercontent.com/assets/2214896/12901558/5a64ae98-ce8a-11e5-879c-3fd3dca1b253.png)

and the Japanese version of same:
![jap](https://cloud.githubusercontent.com/assets/2214896/12901634/b431e940-ce8a-11e5-9000-08ce6c674e27.png)

In both cases, CEN64 was launched without -controller options on the command line.

**Comment by vgturtle127** [comment]
@jkbenaim Oh, crap! I didn't know this was Pokemon Stadium. I should've seen all the Pokemon references just in the screenshot...Guess I need to play more N64/Pokemon games... :blush: 

@mikeryan Sorry, I assumed that what he was talking about when he said the error was correct, I though he meant it was actually about the controllers and that it was relevant. That's why I wanted to know.

Based off of the English message, it appears whatever is wrong must take place during the check of the game pak/controllers, right? If its a region-specific issue, I still can't get what it would be, though.

I would try and test it with other games, but I can't get CEN64 to build anymore, so I give up. :disappointed:

**Comment by tj90241** [comment]
I'm not a PIF expert by any means. If I had to guess, I would think this is a core bug. I'm pretty sure the PIF uses the same protocol byte-for-byte regardless of the region.

When you ran the NTSC-J version of the game, did you launch with an NTSC-J PIFROM?

**Comment by mikeryan** [comment]
Pretty sure this is caused by 14fe91df. No need to read so far into it guys.

**Comment by vgturtle127** [comment]
> No need to read so far into it guys

It seems I have a problem with that. :disappointed:
