### ISSUE TITLE
Unknown CIC type; is this a byte-swapped ROM?

### ISSUE THREAD

**Issue by orbea** [tj90241/cen64#47]
When trying to start most roms I encounter `Unknown CIC type; is this a byte-swapped ROM?`. What does this mean? These roms start correctly for other n64 emulators. Are there any other details I can provide to help debug this? Potentially `.z64` roms work more often than `.n64` or `.v64`.

For example these start.
```
Kirby 64.v64
Legend of Zelda, The - Majora's Mask (U) [!].z64
Ogre Battle 64 - Person of Lordly Caliber (J) (V1.1) [!].z64
```
These don't start
```
Super Smash Bros. (USA).n64
Starfox 64.v64
Zelda OoT 64.v64
```

**Comment by MoochMcGee** [comment]
v64 and n64 roms don't work in cen64 m8

**Comment by orbea** [comment]
That doesn't explain why `Kirby 64.v64` did work. If they don't work what can be done to make them work? If cen64 has any current use it is to test accuracy and that is kind of hard if the roms don't start.

**Comment by mikeryan** [comment]
Kirby 64.v64 was misnamed. If it boots in cen, it's non byteswapped and should be named .z64.

Automatically byte swapping ROMs is on the TODO list, but for now just use .z64 ROMs.

**Comment by orbea** [comment]
Alright, thanks for the explanation. I will leave this open until that is done, feel free to close this sooner if you prefer.

**Comment by tj90241** [comment]
> Automatically byte swapping ROMs is on the TODO list, but for now just use .z64 ROMs.

I've been very insistent in the past that z64 is the only format that will ever be supported by CEN64, and I very much intend to keep fight to keep it that way. I'll take the discussion offline as to why.

For future reference:
N64 has three ROM formats (one for each of the three dumpers that proliferated during the console's lifetime). Each dumper produced a different format (more specifically, they dumped the ROM in different endianness-es).

While most emulators support all three formats, CEN64 only supports the format that is a true clone of what the N64 carts are: the big-endian format. Generally, the emulation community uses the file extension ".z64" to indicate this format of ROM.

**Comment by orbea** [comment]
Thanks for the respsonse, but I guess that is a little unfortunate. However there seems to be a work around with at least with some roms.
```
dd conv=swab <rom.v64 >rom.z64
```
This worked with the game Wonder Project J2.

https://unix.stackexchange.com/questions/239543/is-there-a-oneliner-that-converts-a-binary-file-from-little-endian-to-big-endian

**Comment by tj90241** [comment]
Yep, that'll work for z64 to v64.

It's unfortunate and I imagine a lot of people aren't going to like it. However, consider that it's VERY hard to correctly tell whether or not a ROM is formatted in the endian of the emulator's liking.

Every open-source emulator I have looked at just looks at the first few bytes of the ROM and expects that all ROMs use the same data for the header. That's a hack job that just so happens to work for (all? most?) commercial carts -- but there's no guarantee that all carts use the same values for those fields. So if somebody comes along and changes that field, oh well... your endianness detection algorithm is now defunct.

There's no reason that it should be this way, either. Everyone just should use one format.

**Comment by orbea** [comment]
That explanation does indeed help me understand the reasoning, thanks.

**Comment by beannaich** [comment]
I tried to make a similar argument when designing my emulators, and while I agree with you in theory I cannot agree with you in practice. Being inflexible like this only pushes people away, for examples of this just search for the drama that ensued when byuu forced one file format in BSNES. Most people couldn't possibly care less if they have the correct file format or not.

As far as detection goes, checking the first few bytes **does** work for most commercial games. It at least works for the games that 99% of your users will be playing. I believe this approach is throwing the baby out with the bath water, and it heavily dampens the excitement around both CEN64 and cycle accurate emulators in general. Imagine hearing that finally someone is deciding to give the N64 the focus it deserves, you download the emulator and try to boot a game only to find out that the author of the emulator got a wild hare up his ass and decided to not support a widely used format.

The cat is out of the bag, and unless you have access to every user's computer and will do the conversions of their games for them then no one is going to be on board with you. Add to that the fact that detection/conversion could be a whole 10 lines of C, and you're just going to end up annoying people.

Don't allow a hypothetical 1% of games to stop you from fixing the absolutely real 99% of games.

**Comment by mikeryan** [comment]
We've had a lot of offline conversation about this, and I believe we've convinced MarathonMan of this position.

For what it's worth, most of us involved on this project share your belief and would happily implement any middle of the road solution. The bossman is a little curmudgeonly, but he can be reasoned with :)

**Comment by beannaich** [comment]
@mikeryan Glad to hear it :smile:

I will gladly roll my own solution and pull request it if no one wants to do it themselves.

**Comment by tj90241** [comment]
I still maintain that checking the first few bytes is a completely unacceptable solution, and it will never be accepted as such. @mikeryan swayed my mind because proposed a scheme which is much more general.

Though, I'm glad you mentioned byuu, because I salute him for what he did and his efforts. It was absolutely the right decision to make and I'm glad he stuck with it.

While I still maintain that the _proper_ solution is to force everyone to fix their ROM sets, I'm not going to bully developers and prevent them from making a PR that solves the problem well-enough so that it beats all the corner cases. At the same time, however, I won't invest any time into writing that code. :-p

**Comment by beannaich** [comment]
@tj90241 Absent a method of checking the first few bytes, which is completely reliable for most cases and simple, the only other viable solution I can think of is one of heuristics. In such a system however, the first few bytes would still absolutely be part of the initial guess as to the byte-order of a file. This isn't as hacky as you'd think, text files are encoded with a BOM that allows them to detect byte-order. While the first few bytes in a N64 cartridge dump aren't explicitly allocated for that purpose, they do have the same property. I believe one could easily get away with checking the first few bytes and looking at the extension to form a pretty good guess as to the byte order, and other locations could be checked in cases where the match is ambiguous.

Failing that then a hash check would be the only reasonable alternative, but you'd have to keep hashes for each byte-ordered variant of each game. That might be a bit much to maintain. Let's be clear though, file hashes wouldn't be much better than checking a few known bytes of interest in this case.

This is the ugly reality of file formats, and there isn't a very good way around it.

**Comment by tj90241** [comment]
The problem with the 99% fixes is chiefly that when you pile a lot of 99% fixes on top of each other, you get a result that is only 90% accurate: (0.99^10 = 0.904382...). If a solution isn't going to work 100% of the time, it's not good enough for me! :-p

The suggestion that @mikeryan gave was to basically perform the a similar check that the PIF/CIC use during IPL. If the check fails, then byteswap the ROM and perform the check again. If it still fails, then byteswap a third time (to account for the three file formats floating around) and perform the check again. If all three checks fail, then bail out.

It's still in theory possible to get a collision when you do this, it is detectable and we can have an error raised for that (incredibly unlikely) case.

**Comment by beannaich** [comment]
@tj90241 Doesn't sound like a 100% solution to me, better discard it. :stuck_out_tongue:

No solutions to this problem work for 100% of cases, but 99% is a hell of a lot better than 0%. And I don't agree with your math. When a certain solution works, no other branches are tried for that case. Successive branches are then tried on smaller and smaller sets, like so:

```
1000.0 - (1000.0 * 0.99) = 10.00 bad cases
  10.0 - (  10.0 * 0.99) =  0.10 bad cases
   0.1 - (   0.1 * 0.99) =  0.01 bad cases
```
Basically, asymptoting towards 100%. Even with your other math, I'll take 0.99^10 over 0 any day.

**Comment by tj90241** [comment]
Don't tempt me ;) If I had it my way, I would tell everyone to use big-endian ROMs or beat it.

The math is sound. If I have a fairly-weighted coin, the probability I flip heads twice in a row is exactly 1/4th (heads heads, heads tails, tails heads, tails tails). Or equivalent stated, 1/2 * 1/2 = 1/4.

We can apply similar reasoning to a series of hacks. Each hack has a 99% probability that it works correctly. If any hack fails, the user's experience is impacted. If I have ten hacks that sit on top of each other: (99/100) ^ 10 = 0.904382...

**Comment by beannaich** [comment]
Except we aren't talking probabilities here, the set of N64 binary images is essentially fixed (aside from the homebrew community, and they typically compile for _every_ format), so a given check can be given a fixed value for how many cases it covers. Knowing that, and knowing that each check (or hack as you like to call them) will be applied in turn to progressively more specific cases, I can conclude that your mathematical model doesn't work for this scenario.

More and more checks will push the asymptote closer to 100%, they can't possibly detract from it in any way.

Math aside, what evil is there in checking specific header bytes for information?

**Comment by tj90241** [comment]
Reasoning with random input is good practice in this case. If you want bulletproof software, you're shooting yourself in the foot by making assumptions about how some piece of input should be classified. The entire reason why we're debating over this to begin with is that it has many times been suggested that CEN64 simply look at the first four bytes in the header. Of course I can get really close to an asymptote given a fixed set of input -- look where that reasoning got us in terms of other N64 emulators. "Close, but no cigar..."

What happens if we start fuzzing CEN64 with something like AFL and it flips one of the first four bytes of the ROM image? We get a bunch of failure cases where a possible valid ROM is rejected.

It's as simple as this: something that runs on the console should also run on CEN64. I can change bytes in the header and have things still run fine on the console, but break those kinds of algorithms. I don't want to commit that kind of code.

**Comment by beannaich** [comment]
Right now CEN64 loads absolutely 0 ROMs it doesn't like, even with the basic detection scheme outlined (reviled?) in this thread, the user story for this case improves drastically. If problems are found with it, it can always be improved/replaced/etc, but to reject the idea outright is ludicrous.

Let's say we implement the detection scheme, and a user reports that it fails for a specific .v64 ROM. The question you should ask is, "is the user any worse off in that case than they are today?" And the answer to that is no.

You're worried that a code change **might** allow a few ROMs to fail when currently they **all** fail. I like you and the emulator, but you are being thick headed on your approach here.

**Comment by tj90241** [comment]
I don't think I'm being thick headed because I already stated that I would accept a commit which handles this issue in the manner in which @mikeryan proposed. If you want to suggest another way to do it, we can discuss that. Determining the endian-ness of a ROM based on the first four bytes is just simply a no-go and won't be merged.

In the (adapted) words of Guido van Rossum:

Flames, pleas to reconsider, etc., to /dev/null.

Congratulations gracefully accepted.

It's still my emulator! :-)

**Comment by beannaich** [comment]
Okay, if you want to go down the road of trying to model reality then I will propose a different solution. The real N64 only accepts images in it's native byte order, and will simply refuse to boot any games that don't pass the checks in the PIF/CIC. It doesn't do any byte re-ordering byte itself, and is very rigid.

In this sense, .v64/.n64/.anythinghere64 more closely resemble games from another console. Imagine a fictitious game console called the V64, and the people who played it as kids dumped all the images into the .v64 format, which isn't compatible with the .z64 format because V64 games weren't compatible with the N64 anyways.. at least not directly. Now imagine that the creators of the V64 noticed that their system was completely compatible with the N64 aside from byte order, and they decided to build an adapter block that allows their games to run on the N64. A contrived example, sure, but it does model something that **might** happen in reality. There are several examples of similar adapter blocks that allowed games from one console to be played on another: the Super Game Boy, the Game Boy Advance Player, etc. Now let's assume that the actual implementation of these fictitious V64 to N64 blocks is lost to history, but we still want to emulate it's behavior (High level only, since we don't know how it worked it's magic).

With that out of the way, my proposal is simple:
If a file with any extension other than .z64 is loaded, simulate a user plugging the cartridge into an adapter block then plugging the adapter block in to the N64 proper. The implementation details of the adapter block are third party and irrelevant, and more than one such adapter block might exist. This isn't to say that the converting should be down outside the emulator core, think of it as emulating a different peripheral input device.

**Comment by tj90241** [comment]
This V64 system you describe still boots off a standard cart though (it needs to make use of the lockout chip), so the problem is still the same... you would have to verify the boot cart and figure out what CIC it uses, etc.  :-)

The thread is being locked and closed. If someone wants to submit a PR, open another issue.
